### ISSUE TITLE
JSON fields are not supported

### ISSUE THREAD

**Issue by oltur** [nakatamixi/spanner-er#7]
Error:
2022/12/29 22:13:10 :10: got "JSON", want scalar type
JSON is a normal type and should be supported, at least as a black box

**Comment by sh0z3n** [comment]
Set the Default App for JSON Files · Go to Settings > Apps > Default Apps, then choose Set Default by File type
this  should work if u r using a windows 8 or +

**Comment by oltur** [comment]
I am on Mac, and the problem is that Google parser does not support JSON as well. Can't work this around

**Comment by nktks** [comment]
Thanks for creating issue.
This caused that `spanner-er` used old version of `cloud.google.com/go/spanner`.
I updated at https://github.com/nktks/spanner-er/pull/8
